#!/usr/bin/env bash
set -euo pipefail

WRITE_ENV=""
CHECK_DOCKER=1

while [ "$#" -gt 0 ]; do
  case "$1" in
    --write-env)
      WRITE_ENV="${2:-}"
      shift 2
      ;;
    --skip-docker)
      CHECK_DOCKER=0
      shift
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 2
      ;;
  esac
done

info() { printf "==> %s\n" "$*"; }
warn() { printf "WARN: %s\n" "$*" >&2; }
fail() { printf "ERROR: %s\n" "$*" >&2; exit 1; }

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

docker_cmd() {
  if docker ps >/dev/null 2>&1; then
    printf "docker"
    return 0
  fi
  if command_exists sudo && sudo -n docker ps >/dev/null 2>&1; then
    printf "sudo docker"
    return 0
  fi
  return 1
}

detect_l4t() {
  local version=""
  if command_exists dpkg-query; then
    version="$(dpkg-query -W -f='${Version}' nvidia-l4t-core 2>/dev/null | sed 's/-.*//' || true)"
  fi
  if [ -z "$version" ] && [ -f /etc/nv_tegra_release ]; then
    version="$(sed -n 's/^# R\([0-9.]*\).*/\1/p' /etc/nv_tegra_release | head -n 1)"
  fi
  printf "%s" "$version"
}

write_profile_env() {
  local file="$1"
  mkdir -p "$(dirname "$file")"
  cat > "$file" <<EOF
# Generated by deepstream-lpr-app/scripts/jetson-preflight.sh
DEEPSTREAM_PROFILE=$DEEPSTREAM_PROFILE
JETPACK_VERSION=$JETPACK_VERSION
L4T_VERSION=$L4T_VERSION
CUDA_VER=$CUDA_VER
TENSORRT_VERSION=$TENSORRT_VERSION
DEEPSTREAM_VERSION=$DEEPSTREAM_VERSION
DEEPSTREAM_IMAGE=$DEEPSTREAM_IMAGE
DEEPSTREAM_BASE_IMAGE=$DEEPSTREAM_BASE_IMAGE
PYDS_WHEEL_URL=$PYDS_WHEEL_URL
MODEL_BUILDER_IMAGE=$MODEL_BUILDER_IMAGE
MODEL_BUILDER_BASE_IMAGE=$MODEL_BUILDER_BASE_IMAGE
MODEL_BUILDER_AUTO_BUILD=1
DOCKER_RUNTIME_ARGS="--runtime nvidia"
DEEPSTREAM_YOLO_REPO=https://github.com/marcoslucianops/DeepStream-Yolo.git
DEEPSTREAM_YOLO_REF=2894babce8e75c49115dbe0c7b516289ed853565
EOF
}

ARCH="$(uname -m)"
L4T_VERSION="$(detect_l4t)"

DEEPSTREAM_PROFILE="unsupported"
JETPACK_VERSION="unknown"
CUDA_VER="unknown"
TENSORRT_VERSION="unknown"
DEEPSTREAM_VERSION="unknown"
DEEPSTREAM_IMAGE="camera-monitor-deepstream-runtime:local"
DEEPSTREAM_BASE_IMAGE="nvcr.io/nvidia/deepstream:7.0-triton-multiarch"
PYDS_WHEEL_URL="https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/releases/download/v1.1.11/pyds-1.1.11-py3-none-linux_aarch64.whl"
MODEL_BUILDER_IMAGE="deepstream-lpr-model-builder:local"
MODEL_BUILDER_BASE_IMAGE="ultralytics/ultralytics:latest-jetson-jetpack6"

case "$L4T_VERSION" in
  36.4*)
    DEEPSTREAM_PROFILE="jp61-ds71"
    JETPACK_VERSION="6.1"
    CUDA_VER="12.6"
    TENSORRT_VERSION="10.3"
    DEEPSTREAM_VERSION="7.1"
    DEEPSTREAM_BASE_IMAGE="nvcr.io/nvidia/deepstream:7.1-triton-multiarch"
    PYDS_WHEEL_URL="https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/releases/download/v1.2.0/pyds-1.2.0-py3-none-linux_aarch64.whl"
    ;;
  36.3*)
    DEEPSTREAM_PROFILE="jp60-ds70"
    JETPACK_VERSION="6.0"
    CUDA_VER="12.2"
    TENSORRT_VERSION="8.6"
    DEEPSTREAM_VERSION="7.0"
    DEEPSTREAM_BASE_IMAGE="nvcr.io/nvidia/deepstream:7.0-triton-multiarch"
    PYDS_WHEEL_URL="https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/releases/download/v1.1.11/pyds-1.1.11-py3-none-linux_aarch64.whl"
    ;;
  36.2*)
    DEEPSTREAM_PROFILE="jp60dp-ds64"
    JETPACK_VERSION="6.0 DP"
    CUDA_VER="12.2"
    TENSORRT_VERSION="8.6"
    DEEPSTREAM_VERSION="6.4"
    DEEPSTREAM_BASE_IMAGE="nvcr.io/nvidia/deepstream:6.4-triton-multiarch"
    PYDS_WHEEL_URL="https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/releases/download/v1.1.10/pyds-1.1.10-py3-none-linux_aarch64.whl"
    warn "L4T 36.2 / JetPack 6.0 DP is detected. Prefer JetPack 6.0 GA or 6.1 GA for production."
    ;;
  35.*)
    DEEPSTREAM_PROFILE="jp5-unsupported"
    JETPACK_VERSION="5.x"
    fail "This product Docker path targets JetPack 6 / Ubuntu 22.04. Detected L4T $L4T_VERSION. Upgrade the Jetson to JetPack 6.x, or create a JetPack 5-specific image set before deploying."
    ;;
  "")
    fail "Could not detect Jetson L4T version. Run this on a Jetson device with nvidia-l4t-core installed."
    ;;
  *)
    fail "Unsupported Jetson L4T version: $L4T_VERSION. Add a profile in scripts/jetson-preflight.sh before deploying."
    ;;
esac

if [ "$ARCH" != "aarch64" ]; then
  fail "This product deploy path must run on Jetson aarch64. Detected: $ARCH."
fi

info "Detected Jetson profile: $DEEPSTREAM_PROFILE"
info "L4T $L4T_VERSION, JetPack $JETPACK_VERSION, CUDA $CUDA_VER, TensorRT $TENSORRT_VERSION, DeepStream $DEEPSTREAM_VERSION"
info "DeepStream base image: $DEEPSTREAM_BASE_IMAGE"

if [ "$CHECK_DOCKER" = "1" ]; then
  command_exists docker || fail "Docker is not installed. Install Docker first, then rerun this script."
  DOCKER_BIN="$(docker_cmd || true)"
  if [ -z "$DOCKER_BIN" ]; then
    warn "Docker exists but cannot be accessed without an interactive sudo password. The installer can still continue, but Docker verification is skipped. Add the user to the docker group for unattended installs."
  else
    $DOCKER_BIN compose version >/dev/null 2>&1 || fail "Docker Compose plugin is missing. Install docker-compose-plugin."
    if ! $DOCKER_BIN info 2>/dev/null | grep -qi "nvidia"; then
      warn "Docker info does not list an NVIDIA runtime. Install nvidia-container or nvidia-container-toolkit if DeepStream containers cannot access GPU."
    fi
  fi
fi

if [ -n "$WRITE_ENV" ]; then
  write_profile_env "$WRITE_ENV"
  info "Wrote detected profile env: $WRITE_ENV"
fi
